#!/usr/bin/env bash

declare -A HEXMAP=(
  [Cinema]=x03
  [Scenery]=x0b
  [sRGB]=x0d
  [sRGB_Reset]=x0e
  [Racing]=x11
  [RTS_RPG]=x12
  [FPS]=x13
)

get_hex_value() {
  local name=$1
  if [[ -v HEXMAP[$name] ]]; then
    echo "${HEXMAP[$name]}"
  else
    echo "Error: unknown name '$name'" >&2
    exit 1
  fi
}

file="/tmp/gamevisual_previous"
default="sRGB"
value=$default

# Check if the parameter is "previous"
if [[ "$1" == "previous" ]]; then
    if [[ -f "$file" ]]; then
        value=$(cat "$file")
    else
        value=$default
    fi
else
    value=$(get_hex_value "${1:-$default}")
fi

# Store the current value to file 
ddcutil --model VG279 getvcp xdc --terse | cut -d " " -f 4 > "$file"

# Execute the command with the value
ddcutil --model VG279 setvcp xdc "$value" > /dev/null
