#!/usr/bin/env bash

file="/tmp/gamevisual_previous"
default="x0d"
value=$default

# Check if the parameter is "previous"
if [[ "$1" == "previous" ]]; then
    if [[ -f "$file" ]]; then
        value=$(cat "$file")
    else
        value=$default
    fi
else
    value=${1:-$default}
fi

# Store the current value to file 
ddcutil --model VG279 getvcp xdc --terse | cut -d " " -f 4 > "$file"

# Execute the command with the value
ddcutil --model VG279 setvcp xdc "$value" > /dev/null

